% activate = 'system/MatrixOperations/SVDdecomposition'
function model = actport_svd_decomposition(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    use_matrices = strcmp(char(get_parameter(model, block_id, 'decomptyp', '0')), '1');

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');
    if use_matrices
        block.Script = sprintf([...
            'function [s, u, v] = f(x)\n',...
            '%%#codegen\n'...
            '    [u, s, v] = svd(x);\n'...
            'end\n'...
        ]);
    else
        block.Script = sprintf([...
            'function s = f(x)\n',...
            '%%#codegen\n'...
            '    s = svd(x);\n'...
            'end\n'...
        ]);
    end

    set_common_parameters(model, block_id, model_path);
end
