% activate = 'system/MatrixOperations/Eigenvalues'
function model = actport_eigenvalues(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    eigenvectors = strcmp(get_parameter(model, block_id, 'decomptyp', '0'), '1');

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');

    if eigenvectors
        block.Script = sprintf([...
            'function [d,v] = f(x)\n'...
            '%%#codegen\n'...
            '[v,d] = eig(x);\n'...
            'end\n'...
        ]);
    else
        block.Script = sprintf([...
            'function e = f(x)\n'...
            '%%#codegen\n'...
            'e = eig(x);\n'...
            'end\n'...
        ]);
    end

    set_common_parameters(model, block_id, model_path);
end
