% activate = 'system/MatrixOperations/MatrixNorm'
function model = matrix_norm(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');

    norm_type = char(strrep(get_parameter(model, block_id, 'normtype', '2-Norm'), '''', ''));

    switch norm_type
        case '1-Norm'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = norm(x, 1);\n'...
                'end\n'...
            ]);
        case '2-Norm'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = norm(x, 2);\n'...
                'end\n'...
            ]);
        case 'Inf-Norm'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = norm(x, inf);\n'...
                'end\n'...
            ]);
        case 'Frobenius-Norm'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = norm(x, ''fro'');\n'...
                'end\n'...
            ]);
    end

    set_common_parameters(model, block_id, model_path);
end
