% activate = 'system/MatrixOperations/LUFactorization'
function model = actport_lu_factorization(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');

    provide_permutation_matrix = strcmp(get_parameter(model, block_id, 'plu', '0'), '1');

    if provide_permutation_matrix
        block.Script = sprintf([...
            'function [l,u,e] = f(x)\n'...
            '%%#codegen\n'...
            '[l,u,e] = lu(x);\n'...
            'end\n'...
        ]);
    else
        block.Script = sprintf([...
            'function [l,u] = f(x)\n'...
            '%%#codegen\n'...
            '[l,u] = lu(x);\n'...
            'end\n'...
        ]);
    end

    set_common_parameters(model, block_id, model_path);
end
