% activate = 'system/MatrixOperations/QRFactorization'
function model = actport_qr_factorization(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    permutation_matrix = strcmp(char(get_parameter(model, block_id, 'pqr', '0')), '1');

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');
    if permutation_matrix
        block.Script = sprintf([...
            'function [q, r, e] = f(x)\n',...
            '%%#codegen\n'...
            '    [q, r, e] = qr(x);\n'...
            'end\n'...
        ]);
    else
        block.Script = sprintf([...
            'function [q, r] = f(x)\n',...
            '%%#codegen\n'...
            '    [q, r] = qr(x);\n'...
            'end\n'...
        ]);
    end

    set_common_parameters(model, block_id, model_path);
end
