% activate = 'system/SignalGenerators/Toggle'
function model = actport_toggle(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    first = get_parameter(model, block_id, 'firstvalue', '1');
    second = get_parameter(model, block_id, 'secondvalue', '-1');
    type = get_parameter(model, block_id, 'ot', '''double''');

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');
    block.Script = sprintf([...
        'function y = f()\n'...
        '%%#codegen\n'...
        '   persistent flag;\n'...
        '   if isempty(flag)\n'...
        '       flag = true;\n'...
        '   end\n'...
        '   if flag\n'...
        '       flag = false;\n'...
        '       aux = %1$s;\n'...
        '   else\n'...
        '       flag = true;\n'...
        '       aux = %2$s;\n'...
        '   end\n'...
        '   y = cast(aux, %3$s);\n'...
        'end\n'...
    ], first, second, type);

    set_common_parameters(model, block_id, model_path);
end
