% activate = 'system/MatrixOperations/FFT'
function model = actport_fft(model, block_id, model_path)
    import actport.model.Matlab.*

    name = get_name(model, block_id);
    block_path = sprintf('%s/%s', model_path, name);

    add_block('simulink/User-Defined Functions/MATLAB Function', block_path);
    sf = sfroot();
    block = sf.find('Path', block_path, '-isa', 'Stateflow.EMChart');

    fft_mode = char(strrep(get_parameter(model, block_id, 'direction', 'FFT'), '''', ''));

    switch fft_mode
        case 'FFT'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = fft(x);\n'...
                'end\n'...
            ]);
        case 'IFFT'
            block.Script = sprintf([...
                'function y = f(x)\n'...
                '%%#codegen\n'...
                'y = ifft(x);\n'...
                'end\n'...
            ]);
    end

    set_common_parameters(model, block_id, model_path);
end
